//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeManageWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTS
    {
        public int DTSID { get; set; }
        public System.DateTime DTSDate { get; set; }
        public int DTSTasksID { get; set; }
        public int DTSUserLoginID { get; set; }
        public int DTSActivityID { get; set; }
        public string DTSTimeFrom { get; set; }
        public string DTSTimeTill { get; set; }
        public string DTSHours { get; set; }
        public string DTSStatus { get; set; }
    }
}
