//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeManageWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC
    {
        public int QCID { get; set; }
        public string QCDate { get; set; }
        public string QCBugs { get; set; }
        public string QCProjectID { get; set; }
        public string QCUserLoginID { get; set; }
    }
}
